### ISSUE TITLE
test: basic rule for the c2c translator

### ISSUE THREAD

**Issue by Jonas239** [pvs-hd-tea/TCrules#12]
To achieve a minimal viable prototype we need to have a first set of rules for the translation and test them on correctness and usability for the project.

**Comment by Jonas239** [comment]
...and test them on correctness and usability for the project.

**Comment by vivkaz** [comment]
The predefined basic rule '(number-variable) ALLOCATION' was tested successfully for all three languages. It differs between int, float and double based on the length of the number.
