### ISSUE TITLE
feat: translate while loops

### ISSUE THREAD

**Issue by Jonas239** [pvs-hd-tea/TCrules#60]
look for while statement, determine the condition and  consequence clauses, translate them

Example: 
while a > b:
&nbsp;&nbsp;&nbsp;print("a is greater than b")
&nbsp;&nbsp;&nbsp;a = a - 1
&nbsp;&nbsp;&nbsp;b = b + 1

**Comment by vivkaz** [comment]
Current state could be seen on the translations of 'test' and 'test_blocks' files from all three languages. The translations are stored in tree-sitter-v2/data/translations/
